### ISSUE TITLE
build.py: torURL doesn't exist

### ISSUE THREAD

**Issue by Nekro5o** [emcruise/TorRootkit#5]
I tried the project and ran into an error on the client side:
- The build.py tries to pull the tor expert bundle from "https://www.torproject.org/dist/torbrowser/10.0.12/tor-win32-0.4.5.6.zip"
- That URL does not exist, resulting in an error while trying to unpack: "Error while unpacking tor library"

Fix:
- change Line 15 in build.py to:     torURL = 'https://dist.torproject.org/torbrowser/10.0.14/tor-win32-0.4.5.7.zip'
- The client works perfectly fine with that URL, even though it's a newer version of Tor than used before

**Comment by emcruise** [comment]
Thanks for notifying me, the URL went out of date. I updated the main branch. Next time make a Pull-Request :).
